### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by crack00r** [rudipf/pirate_feedback#10]
Hallo, gibt es irgendwo eine aktuelle Installationsanleitung für nen aktuelles Debian?

**Comment by crack00r** [comment]
http://wigbold8.piratenpartei-bayern.de/releases/pirate_feedback-v1.2.2.tar.bz2 
gibt es leider nicht mehr

**Comment by rudipf** [comment]
Hi,
ich habe https://wiki.piratenpartei.de/Pirate_Feedback/Installation#Files entsprechend ergänzt.
Tendenziell habe ich mich seinerzeit auch eher "durchgekämpft" und wäre Dir dankbar wenn Du die Installationsanleitng nach Bedarf ergänzt.
Danke,Rudi

**Comment by rudipf** [comment]
Installation um zwei KLeinigkeiten ergänzt
