### ISSUE TITLE
operator does not exist

### ISSUE THREAD

**Issue by crack00r** [rudipf/pirate_feedback#11]
psql:core.sql:440: ERROR:  operator does not exist: boolean = integer
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
www-data@j314465:/opt/liquid_feedback_core$

**Comment by rudipf** [comment]
Hi,
kann ich nicht nachvollziehen.
Besteht der Fehler auch für die core.sql von hier ?

**Comment by rudipf** [comment]
Doch gefunden. Und gefixt
